/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BookingSrvListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheBookingSrvListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheBookingSrvListGenerated.onFilterBar().iCheckFilterField({ property: "CustomerId" });
            Then.onTheBookingSrvListGenerated.onFilterBar().iCheckFilterField({ property: "BookingDate" });
            Then.onTheBookingSrvListGenerated.onFilterBar().iCheckFilterField({ property: "OverallStatus" });
            Then.onTheBookingSrvListGenerated.onFilterBar().iCheckFilterField({ property: "CustomerCity" });
            Then.onTheBookingSrvListGenerated.onFilterBar().iCheckFilterField({ property: "ConfirmFlag" });
            Then.onTheBookingSrvListGenerated.onFilterBar().iCheckFilterField({ property: "Priority" });
        });

        opaTest("Add semantic key properties to filter bar", function (Given, When, Then) {
            When.onTheBookingSrvListGenerated.onFilterBar().iOpenFilterAdaptation();
            When.onTheBookingSrvListGenerated.onFilterBar().iAddAdaptationFilterField({ property: "BookingId" });
            When.onTheBookingSrvListGenerated.onFilterBar().iConfirmFilterAdaptation();
            Then.onTheBookingSrvListGenerated.onFilterBar().iCheckFilterField({ property: "BookingId" });
            // When.onTheBookingSrvListGenerated.onFilterBar().iChangeFilterField({ property: "BookingId" }, "<value to filter>", false);
            // When.onTheBookingSrvListGenerated.onFilterBar().iExecuteSearch();
            // Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckRows();
            // When.onTheBookingSrvListGenerated.onTable(defaultTableId).iSelectRows(0);
            // Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckAction("<Action Name>", { enabled: true });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheBookingSrvListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheBookingSrvListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckCreate({ visible: true });
            // When.onTheBookingSrvListGenerated.onTable(defaultTableId).iPressCreate();
            // When.onTheBookingSrvListGenerated.onTable(defaultTableId).iPressDelete();
            Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckDelete({ visible: true });
            // When.onTheBookingSrvListGenerated.onTable(defaultTableId).iPressAction("Cancel");
            Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckAction("Cancel", { enabled: false });
            // When.onTheBookingSrvListGenerated.onTable(defaultTableId).iPressAction("Discount");
            Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckAction("Discount", { enabled: true });
            Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"6":{"header":"Price Chart"},"8":{"header":"Rating"},"9":{"header":"Completion"},"BookingId":{"header":"Booking ID"},"CustomerId":{"header":"Customer"},"BookingDate":{"header":"Booking Date"},"OverallStatus":{"header":"Status"},"Priority":{"header":"Priority"},"TotalPrice":{"header":"Total Price"},"ConfirmFlag":{"header":"Confirmed"},"Description":{"header":"Description"},"CustomerName":{"header":"Contact"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheBookingSrvListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheBookingSrvListGenerated.onTable(defaultTableId).iCheckRows();
            When.onTheBookingSrvListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onTheBookingSrvObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});