/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BookingSrvObjectPageObjectPage journey");

        opaTest("Navigate to BookingSrvObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheBookingSrvListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheBookingSrvListGenerated.onTable().iCheckRows();
            When.onTheBookingSrvListGenerated.onTable().iPressRow(0);

            Then.onTheBookingSrvObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheBookingSrvObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheBookingSrvObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheBookingSrvObjectPageGenerated.onHeader().iCheckAction("Accept" /* , { enabled: true } */);
            // When.onTheBookingSrvObjectPageGenerated.onHeader().iPressAction("Accept");
            Then.onTheBookingSrvObjectPageGenerated.onHeader().iCheckAction("Cancel" /* , { enabled: true } */);
            // When.onTheBookingSrvObjectPageGenerated.onHeader().iPressAction("Cancel");
        });

        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onTheBookingSrvObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "RatingHdr" });
            Then.onTheBookingSrvObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "ProgressHdr" });
            Then.onTheBookingSrvObjectPageGenerated.onHeader().iCheckHeaderFacet({ facetId: "PriceHdr" });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBookingSrvObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheBookingSrvObjectPageGenerated.iPressSectionIconTabFilterButton("General");
            Then.onTheBookingSrvObjectPageGenerated.iCheckSection({ section: "General" });
            When.onTheBookingSrvObjectPageGenerated.iPressSectionIconTabFilterButton("Items");
            Then.onTheBookingSrvObjectPageGenerated.iCheckSection({ section: "Items" });
            Then.onTheBookingSrvObjectPageGenerated.onTable({ property: "_BookingItem" }).iCheckColumns(undefined, {"ItemId":{"header":"Item"},"ProductId":{"header":"Product"},"Quantity":{"header":"Quantity"},"ItemPrice":{"header":"Item Price"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});